FROM python:3.9-slim

RUN pip install mlflow

CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--artifacts-destination", "./mlflow/artifacts", "--serve-artifacts", "--host", "0.0.0.0"]
