# Используем официальный образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы в контейнер
COPY . .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Открываем порт
EXPOSE 8001

# Команда для запуска приложения
CMD ["uvicorn", "models:app", "--host", "0.0.0.0", "--port", "8001"]
